apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: qjc4v0pzl-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/qjc4v0pzl-java-springboot-gitops